# Generated by Django 5.1.3 on 2024-11-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0006_product_img1_product_img2_product_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
